// Generated by knowledge_base/tools/build_knowledge_base.py - do not edit by hand.
LC.registerCatalog({
 "schema": 1,
 "generated_at": "2026-10-10T12:08:09+00:00",
 "weeks": {
  "1": "LLM 是什麼運算元件",
  "2": "AI 協作開發工作流",
  "3": "Context Engineering",
  "4": "從零寫 coding agent",
  "5": "MCP 與工具生態",
  "6": "安全與可靠性",
  "7": "多 agent 與長時間任務",
  "8": "設計 eval",
  "9": "Eval 驅動迭代",
  "10": "推論系統與效能",
  "11": "系統設計模擬",
  "12": "綜合演練"
 },
 "core_lessons": [
  "tokens",
  "sampling",
  "inference",
  "caching",
  "toolbox"
 ],
 "sources": [
  {
   "id": "coding-with-ai",
   "title": "Coding with AI: Examples in Python",
   "author": "Jeremy C. Morgan",
   "publisher": "Manning Publications",
   "year": 2025
  },
  {
   "id": "ai-assisted-programming",
   "title": "AI-Assisted Programming: Better Planning, Coding, Testing, and Deployment（第 1、8、9 章節錄）",
   "author": "Tom Taulli",
   "publisher": "O'Reilly Media",
   "year": 2024
  }
 ],
 "notes": [
  {
   "id": "deep-kv-cache-size",
   "title": "KV cache 到底多大",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 7,
   "attach": "inference",
   "source": null,
   "file": "notes/deep-kv-cache-size.js"
  },
  {
   "id": "deep-logprobs-constrained",
   "title": "取樣之外：logprobs 與受限解碼",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 6,
   "attach": "sampling",
   "source": null,
   "file": "notes/deep-logprobs-constrained.js"
  },
  {
   "id": "deep-prompt-caching-ops",
   "title": "Prompt caching 的運作與監控",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 6,
   "attach": "caching",
   "source": null,
   "file": "notes/deep-prompt-caching-ops.js"
  },
  {
   "id": "deep-tokenizer",
   "title": "Tokenizer 為什麼會影響成本與行為",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 5,
   "attach": "tokens",
   "source": null,
   "file": "notes/deep-tokenizer.js"
  },
  {
   "id": "deep-tool-interface-design",
   "title": "工具介面設計：給模型看的 API",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 7,
   "attach": "toolbox",
   "source": null,
   "file": "notes/deep-tool-interface-design.js"
  },
  {
   "id": "deep-context-budget",
   "title": "Context 預算：放什麼、丟什麼",
   "kind": "deepdive",
   "week": 1,
   "order": 20,
   "minutes": 6,
   "attach": "tokens",
   "source": null,
   "file": "notes/deep-context-budget.js"
  },
  {
   "id": "deep-prefill-decode-speculative",
   "title": "Prefill、decode 與 speculative decoding",
   "kind": "deepdive",
   "week": 1,
   "order": 20,
   "minutes": 7,
   "attach": "inference",
   "source": null,
   "file": "notes/deep-prefill-decode-speculative.js"
  },
  {
   "id": "taulli-abstraction-genai-map",
   "title": "抽象的階梯：LLM 這一層放棄了什麼保證",
   "kind": "lesson",
   "week": 1,
   "order": 30,
   "minutes": 15,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     1,
     6
    ]
   },
   "file": "notes/taulli-abstraction-genai-map.js"
  },
  {
   "id": "book-why-llm-wrong",
   "title": "為什麼 AI 會寫出「看起來對」的錯誤",
   "kind": "lesson",
   "week": 1,
   "order": 40,
   "minutes": 12,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     8,
     15
    ]
   },
   "file": "notes/book-why-llm-wrong.js"
  },
  {
   "id": "book-tool-landscape",
   "title": "AI 開發工具地圖與導入考量",
   "kind": "lesson",
   "week": 1,
   "order": 50,
   "minutes": 12,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     6,
     31
    ]
   },
   "file": "notes/book-tool-landscape.js"
  },
  {
   "id": "glossary",
   "title": "術語表",
   "kind": "lesson",
   "week": 1,
   "order": 90,
   "minutes": 5,
   "attach": null,
   "source": null,
   "file": "notes/glossary.js"
  },
  {
   "id": "staff-terminology-map",
   "title": "術語地圖：把容易混淆的詞分開",
   "kind": "lesson",
   "week": 1,
   "order": 95,
   "minutes": 18,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     1,
     59
    ]
   },
   "file": "notes/staff-terminology-map.js"
  },
  {
   "id": "book-context-and-patterns",
   "title": "Context 從哪來：助手怎麼知道你在做什麼",
   "kind": "lesson",
   "week": 2,
   "order": 10,
   "minutes": 12,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     35,
     36
    ]
   },
   "file": "notes/book-context-and-patterns.js"
  },
  {
   "id": "book-design-first",
   "title": "先設計再生成：從需求到 stub",
   "kind": "lesson",
   "week": 2,
   "order": 20,
   "minutes": 14,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     57,
     85
    ]
   },
   "file": "notes/book-design-first.js"
  },
  {
   "id": "book-failure-modes",
   "title": "AI 輔助開發中真實出現的失敗",
   "kind": "lesson",
   "week": 2,
   "order": 30,
   "minutes": 14,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     101,
     178
    ]
   },
   "file": "notes/book-failure-modes.js"
  },
  {
   "id": "book-ai-testing",
   "title": "用 AI 產生單元測試，以及它的盲點",
   "kind": "lesson",
   "week": 2,
   "order": 40,
   "minutes": 15,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     210,
     230
    ]
   },
   "file": "notes/book-ai-testing.js"
  },
  {
   "id": "book-prompt-fundamentals",
   "title": "Prompt 的基本功：組成與六種基本類型",
   "kind": "lesson",
   "week": 2,
   "order": 50,
   "minutes": 15,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     244,
     264
    ]
   },
   "file": "notes/book-prompt-fundamentals.js"
  },
  {
   "id": "book-prompt-advanced",
   "title": "進階 prompt 技巧：拆解、精煉、控制輸出",
   "kind": "lesson",
   "week": 2,
   "order": 60,
   "minutes": 15,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     265,
     284
    ]
   },
   "file": "notes/book-prompt-advanced.js"
  },
  {
   "id": "book-vibe-coding",
   "title": "Vibe coding 與 agent 工具：什麼時候放手",
   "kind": "lesson",
   "week": 2,
   "order": 70,
   "minutes": 14,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     285,
     298
    ]
   },
   "file": "notes/book-vibe-coding.js"
  },
  {
   "id": "taulli-judging-generated-code",
   "title": "審查 AI 產生的程式碼：用 merge 範例做一次完整審查",
   "kind": "lesson",
   "week": 2,
   "order": 100,
   "minutes": 22,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     21,
     36
    ]
   },
   "file": "notes/taulli-judging-generated-code.js"
  },
  {
   "id": "taulli-safe-refactoring",
   "title": "安全重構：沒有 oracle，就沒有「行為不變」",
   "kind": "lesson",
   "week": 2,
   "order": 110,
   "minutes": 22,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     30,
     34
    ]
   },
   "file": "notes/taulli-safe-refactoring.js"
  },
  {
   "id": "taulli-legacy-and-comprehension",
   "title": "讀懂與移植遺留程式：翻譯不等於現代化",
   "kind": "lesson",
   "week": 2,
   "order": 120,
   "minutes": 20,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     8,
     14
    ]
   },
   "file": "notes/taulli-legacy-and-comprehension.js"
  },
  {
   "id": "taulli-data-ui-api",
   "title": "資料、前端與 API：讓 AI 產生「產生器」，而不是產物",
   "kind": "lesson",
   "week": 2,
   "order": 130,
   "minutes": 22,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     37,
     45
    ]
   },
   "file": "notes/taulli-data-ui-api.js"
  },
  {
   "id": "taulli-debug-review-docs",
   "title": "除錯、文件與程式碼審查：讓 AI 提出假設，由你做實驗",
   "kind": "lesson",
   "week": 2,
   "order": 140,
   "minutes": 22,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     47,
     51
    ]
   },
   "file": "notes/taulli-debug-review-docs.js"
  },
  {
   "id": "taulli-tests-audit-and-prs",
   "title": "稽核 AI 寫的單元測試，以及怎麼寫好 PR 描述",
   "kind": "lesson",
   "week": 2,
   "order": 150,
   "minutes": 25,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     51,
     55
    ]
   },
   "file": "notes/taulli-tests-audit-and-prs.js"
  },
  {
   "id": "taulli-deploy-feedback",
   "title": "部署、維運查詢與使用者回饋：AI 寫的腳本是「有權限的程式碼」",
   "kind": "lesson",
   "week": 2,
   "order": 160,
   "minutes": 25,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     55,
     59
    ]
   },
   "file": "notes/taulli-deploy-feedback.js"
  },
  {
   "id": "staff-task-placement-matrix",
   "title": "舉一反三：任務放置矩陣與導入手冊",
   "kind": "lesson",
   "week": 2,
   "order": 190,
   "minutes": 28,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     1,
     59
    ]
   },
   "file": "notes/staff-task-placement-matrix.js"
  },
  {
   "id": "deep-package-hallucination",
   "title": "套件幻覺：模型編出來的依賴名稱，與一個 CI 檢查",
   "kind": "deepdive",
   "week": 6,
   "order": 10,
   "minutes": 8,
   "attach": "taulli-risk-register",
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     15,
     17
    ]
   },
   "file": "notes/deep-package-hallucination.js"
  },
  {
   "id": "taulli-risk-register",
   "title": "風險登記表：把書中的六類風險變成可管理的控制項",
   "kind": "lesson",
   "week": 6,
   "order": 10,
   "minutes": 25,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     15,
     18
    ]
   },
   "file": "notes/taulli-risk-register.js"
  },
  {
   "id": "deep-license-and-ip",
   "title": "授權與智慧財產：AI 輔助時的最小可行管理",
   "kind": "deepdive",
   "week": 6,
   "order": 20,
   "minutes": 8,
   "attach": "taulli-risk-register",
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     15,
     16
    ]
   },
   "file": "notes/deep-license-and-ip.js"
  },
  {
   "id": "taulli-reading-productivity-evidence",
   "title": "判讀生產力證據：數字背後的研究設計",
   "kind": "lesson",
   "week": 8,
   "order": 10,
   "minutes": 28,
   "attach": null,
   "source": {
    "id": "ai-assisted-programming",
    "pages": [
     6,
     10
    ]
   },
   "file": "notes/taulli-reading-productivity-evidence.js"
  }
 ]
});
