// Generated by knowledge_base/tools/build_knowledge_base.py - do not edit by hand.
LC.registerCatalog({
 "schema": 1,
 "generated_at": "2026-10-04T20:17:01+00:00",
 "weeks": {
  "1": "LLM 是什麼運算元件",
  "2": "AI 協作開發工作流",
  "3": "Context Engineering",
  "4": "從零寫 coding agent",
  "5": "MCP 與工具生態",
  "6": "安全與可靠性",
  "7": "多 agent 與長時間任務",
  "8": "設計 eval",
  "9": "Eval 驅動迭代",
  "10": "推論系統與效能",
  "11": "系統設計模擬",
  "12": "綜合演練"
 },
 "core_lessons": [
  "tokens",
  "sampling",
  "inference",
  "caching",
  "toolbox"
 ],
 "sources": [
  {
   "id": "coding-with-ai",
   "title": "Coding with AI: Examples in Python",
   "author": "Jeremy C. Morgan",
   "publisher": "Manning Publications",
   "year": 2025
  }
 ],
 "notes": [
  {
   "id": "deep-kv-cache-size",
   "title": "KV cache 到底多大",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 7,
   "attach": "inference",
   "source": null,
   "file": "notes/deep-kv-cache-size.js"
  },
  {
   "id": "deep-logprobs-constrained",
   "title": "取樣之外：logprobs 與受限解碼",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 6,
   "attach": "sampling",
   "source": null,
   "file": "notes/deep-logprobs-constrained.js"
  },
  {
   "id": "deep-prompt-caching-ops",
   "title": "Prompt caching 的運作與監控",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 6,
   "attach": "caching",
   "source": null,
   "file": "notes/deep-prompt-caching-ops.js"
  },
  {
   "id": "deep-tokenizer",
   "title": "Tokenizer 為什麼會影響成本與行為",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 5,
   "attach": "tokens",
   "source": null,
   "file": "notes/deep-tokenizer.js"
  },
  {
   "id": "deep-tool-interface-design",
   "title": "工具介面設計：給模型看的 API",
   "kind": "deepdive",
   "week": 1,
   "order": 10,
   "minutes": 7,
   "attach": "toolbox",
   "source": null,
   "file": "notes/deep-tool-interface-design.js"
  },
  {
   "id": "deep-context-budget",
   "title": "Context 預算：放什麼、丟什麼",
   "kind": "deepdive",
   "week": 1,
   "order": 20,
   "minutes": 6,
   "attach": "tokens",
   "source": null,
   "file": "notes/deep-context-budget.js"
  },
  {
   "id": "deep-prefill-decode-speculative",
   "title": "Prefill、decode 與 speculative decoding",
   "kind": "deepdive",
   "week": 1,
   "order": 20,
   "minutes": 7,
   "attach": "inference",
   "source": null,
   "file": "notes/deep-prefill-decode-speculative.js"
  },
  {
   "id": "book-why-llm-wrong",
   "title": "為什麼 AI 會寫出「看起來對」的錯誤",
   "kind": "lesson",
   "week": 1,
   "order": 40,
   "minutes": 12,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     8,
     15
    ]
   },
   "file": "notes/book-why-llm-wrong.js"
  },
  {
   "id": "book-tool-landscape",
   "title": "AI 開發工具地圖與導入考量",
   "kind": "lesson",
   "week": 1,
   "order": 50,
   "minutes": 12,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     6,
     31
    ]
   },
   "file": "notes/book-tool-landscape.js"
  },
  {
   "id": "glossary",
   "title": "術語表",
   "kind": "lesson",
   "week": 1,
   "order": 90,
   "minutes": 5,
   "attach": null,
   "source": null,
   "file": "notes/glossary.js"
  },
  {
   "id": "book-context-and-patterns",
   "title": "Context 從哪來：助手怎麼知道你在做什麼",
   "kind": "lesson",
   "week": 2,
   "order": 10,
   "minutes": 12,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     35,
     36
    ]
   },
   "file": "notes/book-context-and-patterns.js"
  },
  {
   "id": "book-design-first",
   "title": "先設計再生成：從需求到 stub",
   "kind": "lesson",
   "week": 2,
   "order": 20,
   "minutes": 14,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     57,
     85
    ]
   },
   "file": "notes/book-design-first.js"
  },
  {
   "id": "book-failure-modes",
   "title": "AI 輔助開發中真實出現的失敗",
   "kind": "lesson",
   "week": 2,
   "order": 30,
   "minutes": 14,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     101,
     178
    ]
   },
   "file": "notes/book-failure-modes.js"
  },
  {
   "id": "book-ai-testing",
   "title": "用 AI 產生單元測試，以及它的盲點",
   "kind": "lesson",
   "week": 2,
   "order": 40,
   "minutes": 15,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     210,
     230
    ]
   },
   "file": "notes/book-ai-testing.js"
  },
  {
   "id": "book-prompt-fundamentals",
   "title": "Prompt 的基本功：組成與六種基本類型",
   "kind": "lesson",
   "week": 2,
   "order": 50,
   "minutes": 15,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     244,
     264
    ]
   },
   "file": "notes/book-prompt-fundamentals.js"
  },
  {
   "id": "book-prompt-advanced",
   "title": "進階 prompt 技巧：拆解、精煉、控制輸出",
   "kind": "lesson",
   "week": 2,
   "order": 60,
   "minutes": 15,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     265,
     284
    ]
   },
   "file": "notes/book-prompt-advanced.js"
  },
  {
   "id": "book-vibe-coding",
   "title": "Vibe coding 與 agent 工具：什麼時候放手",
   "kind": "lesson",
   "week": 2,
   "order": 70,
   "minutes": 14,
   "attach": null,
   "source": {
    "id": "coding-with-ai",
    "pages": [
     285,
     298
    ]
   },
   "file": "notes/book-vibe-coding.js"
  }
 ]
});
